import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import 'api_service.dart';
import 'app_refresh.dart';
import 'branding_service.dart';

/// LanguageService
///
/// Priority chain for translations:
///  1. API translations (fetched per language code, cached in SharedPreferences)
///  2. Built-in hardcoded English fallback (always present)
///
/// Usage:
///   LanguageService.t('pay_now')           → 'Pay Now' / 'अभी भुगतान करें'
///   LanguageService.currentCode            → 'hi'
///   await LanguageService.setLanguage('hi') → fetch + cache
class LanguageService {
  static String _currentCode = 'en';
  static Map<String, String> _translations = {};

  static String get currentCode => _currentCode;
  static bool get isRtl => ['ar','ur','he','fa'].contains(_currentCode);

  /// Translate a key. Falls back to English, then to the key itself.
  /// Translate a key, then substitute the literal `{symbol}` placeholder
  /// (used by strings that need to embed the apartment's currency, e.g.
  /// "Bills that come to {symbol}0...") with the live currency symbol from
  /// BrandingService. Works for the built-in fallback AND any API-fetched
  /// translation that uses the same placeholder.
  static String t(String key) {
    final raw = _translations[key] ?? _builtinFallback[key] ?? key;
    return raw.contains('{symbol}')
        ? raw.replaceAll('{symbol}', BrandingService.currencySymbol)
        : raw;
  }

  /// Load saved language on app start (before API is available).
  static Future<void> loadSaved() async {
    final prefs   = await SharedPreferences.getInstance();
    _currentCode  = prefs.getString('lang_code') ?? 'en';
    final cached  = prefs.getString('translations_$_currentCode');
    if (cached != null) {
      try {
        _translations = Map<String, String>.from(
            (jsonDecode(cached) as Map).map((k, v) => MapEntry(k.toString(), v.toString())));
      } catch (_) {}
    }
    if (_translations.isEmpty) _translations = Map.from(_builtinFallback);
  }

  /// Set language and fetch fresh translations from the backend.
  /// Call this from profile settings when user changes language.
  static Future<void> setLanguage(String langCode) async {
    try {
      final res = await ApiService().put('/user/language', {'language_code': langCode});
      final raw = (res['translations'] as Map?)?.map(
              (k, v) => MapEntry(k.toString(), v.toString())) ??
          {};
      _apply(langCode, raw);
    } catch (_) {
      // Fallback: try fetching translations only
      await _fetchTranslations(langCode);
    }
  }

  /// Apply branding from login response (which includes translations inline).
  static Future<void> applyFromLogin(Map<String, dynamic> data) async {
    final langCode = data['language'] as String? ?? 'en';
    // If login response includes translations, use them
    if (data['translations'] != null) {
      final raw = (data['translations'] as Map).map(
          (k, v) => MapEntry(k.toString(), v.toString()));
      _apply(langCode, raw);
    } else {
      // Otherwise fetch separately
      await _fetchTranslations(langCode);
    }
  }

  /// Fetch translations from API and cache.
  static Future<void> _fetchTranslations(String langCode) async {
    try {
      final res = await ApiService().get('/translations?lang=$langCode');
      final raw = (res['translations'] as Map?)?.map(
              (k, v) => MapEntry(k.toString(), v.toString())) ??
          {};
      _apply(langCode, raw);
    } catch (_) {
      // API unavailable: use cached or fallback
      _currentCode = langCode;
      AppRefresh.bump();
    }
  }

  static Future<void> _apply(String langCode, Map<String, String> remote) async {
    _currentCode  = langCode;
    // Merge: fallback → remote (remote wins)
    _translations = {..._builtinFallback, ...remote};

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('lang_code', langCode);
    await prefs.setString(
        'translations_$langCode', jsonEncode(_translations));

    // Force the whole app to rebuild so every currently-mounted screen
    // (not just the one that triggered the change) redraws with the new
    // language immediately.
    AppRefresh.bump();
  }

  // ── Built-in English fallback ─────────────────────────────────────────────
  // These are ALWAYS available even when offline.
  // API translations override these for non-English languages.
  static const Map<String, String> _builtinFallback = {
    // ── Fund & Treasurer (Apartment Admin) — added: these keys were used
    // via LanguageService.t() in admin_treasurer_screen.dart / my_fund_screen.dart
    // but had no English fallback here, so they rendered as raw snake_case
    // key text on screen (in ANY language, since this map is the last resort
    // after API translations and before the raw key itself).
    'activate': 'Activate',
    'active_treasurers': 'Active Treasurers',
    'add_treasurer': 'Add Treasurer',
    'adjust': 'Adjust',
    'all_statuses': 'All Statuses',
    'all_types': 'All Types',
    'allocate': 'Allocate',
    'allocate_fund_to': 'Allocate Fund to',
    'apartment_available_balance': 'Apartment Available Balance',
    'available_to_allocate': 'Available to allocate',
    'comment': 'Comment',
    'credit_increase': 'Credit (increase balance)',
    'deactivate': 'Deactivate',
    'debit_decrease': 'Debit (decrease balance)',
    'direction': 'Direction',
    'expense_submitted': 'Expense submitted',
    'facility_deleted': 'Facility deleted',
    'fund_request_submitted': 'Fund request submitted',
    'fund_returned': 'Fund returned',
    'fund_treasurer': 'Fund & Treasurer',
    'held_by_treasurers': 'Held by Treasurers',
    'items_awaiting_review': 'items awaiting review',
    'manual_adjustment': 'Manual Adjustment',
    'max_holding_amount': 'Maximum Holding Amount',
    'max_holding_amount_optional': 'Maximum Holding Amount (optional)',
    'my_balance': 'My Balance',
    'my_fund': 'My Fund',
    'new_plan': 'New Plan',
    'no_activity_yet': 'No activity yet.',
    'no_transactions_found': 'No transactions found.',
    'no_treasurers_yet': 'No treasurers yet.',
    'none': 'None',
    'reason_required': 'Reason is required',
    'request_additional_fund': 'Request Additional Fund',
    'request_fund': 'Request Fund',
    'return_fund': 'Return Fund',
    'reverse': 'Reverse',
    'review_now': 'Review Now',
    'save_adjustment': 'Save Adjustment',
    'submit_request': 'Submit Request',
    'total_apartment_money': 'Total Apartment Money',
    'transactions': 'Transactions',
    'treasurers': 'Treasurers',

    'actions': 'Actions',
    'active': 'Active',
    'active_available_for_booking': 'Active / Available for Booking',
    'active_charge_types_are_included_when_generat': 'Active charge types are included when generating monthly bills. ',
    'activities': 'Activities',
    'add': 'Add',
    'add_a_charge_type_first_from_the_main_charge': 'Add a charge type first from the main Charge Setup screen.',
    'add_a_comment': 'Add a comment...',
    'add_a_tower_first_before_adding_floors': 'Add a tower first before adding floors.',
    'add_advance': 'Add Advance',
    'add_advance_payment': 'Add Advance Payment',
    'add_agreement': 'Add Agreement',
    'add_category': 'Add Category',
    'add_contact': 'Add Contact',
    'add_charge': 'Add Charge',
    'add_comment': 'Add Comment',
    'add_expense': 'Add Expense',
    'add_facility': 'Add Facility',
    'add_flat': 'Add Flat',
    'add_floor': 'Add Floor',
    'add_fund': 'Add Fund',
    'add_one_time_charge': 'Add One-Time Charge',
    'add_resident': 'Add Resident',
    'add_slot': 'Add Slot',
    'add_tower': 'Add Tower',
    'add_tower_first': 'Add Tower First',
    'add_vendor': 'Add Vendor',
    'additional_flats': 'Additional Flats',
    'address_optional': 'Address (optional)',
    'admin': 'Admin',
    'advance_payment_submitted_awaiting_admin_conf': 'Advance payment submitted - awaiting admin confirmation.',
    'agreements': 'Agreements',
    'all': 'All',
    'all_categories': 'All Categories',
    'all_flats_n_same_amount': 'All Flats\n(Same Amount)',
    'all_of_this_resident_s_flats': 'All of this resident\'s flats',
    'all_residents': 'All Residents',
    'all_selected_residents_will_receive_a_push_no': 'All selected residents will receive a push notification.',
    'already_paid_flats_are_not_overwritten_a_lowe': 'Already-paid flats are not overwritten: a lower amount refunds the difference to that flat\'s wallet, a higher amount adds a new payable top-up.',
    'amount': 'Amount',
    'amount_2': 'Amount',
    'amount_optional': 'Amount (optional)',
    'apartment': 'Apartment',
    'apartment_admin': 'Apartment Admin',
    'app_menu_settings': 'App Menu Settings',
    'app_menu_settings_hint': 'Choose which Quick Action and Bottom Nav items show in the app, per apartment.',
    'app_menu_settings_updated': 'App menu settings updated.',
    'configure_menus': 'Configure Menus',
    'quick_action': 'Quick Action',
    'quick_action_hidden_hint': "Unchecked items are hidden from the app's Quick Action grid. Lower order numbers show first.",
    'bottom_nav': 'Bottom Nav',
    'always_shown_first_hint': 'Always shown first (far left) — fixed, not configurable.',
    'flanking_icon_positions': 'Flanking icon positions',
    'position_label': 'Position',
    'centre_raised_button_pick_one': 'Centre (raised) button',
    'save_menu_settings': 'Save Menu Settings',
    'nav_positions_duplicate_warning': 'Two positions have the same item selected — pick a different item for each before saving.',
    'nav_duplicate_confirm': 'One or more Bottom Nav sections have the same item picked for two positions - those sections will fall back to their default layout. Continue saving anyway?',
    'app_identity': 'App Identity',
    'font_family': 'Font Family',
    'app_name': 'App Name',
    'app_name_is_required': 'App name is required',
    'applied_immediately_no_approval_needed_auto_a': 'Applied immediately - no approval needed. Auto-adjusted against any outstanding dues.',
    'apply_to': 'Apply To',
    'approve': 'Approve',
    'approve_advance_payment_q': 'Approve advance payment?',
    'approve_payment_q': 'Approve payment?',
    'approved': 'Approved',
    'area_sq_ft': 'Area (sq ft)',
    'assign': 'Assign',
    'assign_slot': 'Assign Slot',
    'assign_to_resident': 'Assign to Resident *',
    'assigned_to': 'Assigned To',
    'auto_applied_to_future_bills_charges': 'Auto-applied to future bills/charges',
    'available': 'Available',
    'available_plans': 'Available Plans',
    'available_slots': 'Available Slots',
    'available_whether_or_not_an_online_gateway_is': 'Available whether or not an online gateway is set up.',
    'awaiting_confirmation': 'Awaiting Confirmation',
    'back': 'Back',
    'bank_transfer': 'Bank Transfer',
    'bill_number': 'Bill Number',
    'billing': 'Billing',
    'billing_period': 'Billing Period',
    'bills': 'Bills',
    'bills_that_come_to_0_or_that_already_exist_fo': 'Bills that come to {symbol}0, or that already exist for that month, are skipped automatically.',
    'book': 'Book',
    'book_now': 'Book Now',
    'booking_date': 'Booking Date',
    'booking_fee': 'Booking Fee',
    'booking_fee_0_free': 'Booking Fee (0 = free)',
    'booking_request_submitted_for_approval': 'Booking request submitted for approval.',
    'booking_status': 'Booking Status',
    'branding': 'Branding',
    'branding_updated': 'Branding updated!',
    'bulk_notify': 'Bulk Notify',
    'by_category': 'By Category',
    'by_payment_method': 'By Payment Method',
    'by_status': 'By Status',
    'by_tower': 'By Tower',
    'cancel': 'Cancel',
    'cancel_booking': 'Cancel Booking',
    'cancel_request': 'Cancel Request',
    'cancelled': 'Cancelled',
    'cannot_delete_an_occupied_flat_change_status': 'Cannot delete an occupied flat. Change status to Vacant first.',
    'capacity': 'Capacity',
    'car': 'Car',
    'cash': 'Cash',
    'card': 'Card',
    'catch_up_bills': 'Catch-up Bills',
    'catch_up_bills_missed_months_one_resident': 'Catch-up Bills (missed months, one resident)',
    'category': 'Category',
    'category_name': 'Category Name *',
    'change_password': 'Change Password',
    'changes_apply_to_this_apartment_s_app_and_web': 'Changes apply to this apartment\'s app and web portal for all residents.',
    'charge_deleted': 'Charge deleted',
    'charge_name': 'Charge Name *',
    'charge_name_is_required': 'Charge name is required',
    'charge_setup': 'Charge Setup',
    'charge_type_deleted': 'Charge type deleted',
    'charge_updated_paid_flats_reconciled_via_wall': 'Charge updated. Paid flats reconciled via wallet.',
    'check_any_other_flats_this_resident_also_owns': 'Check any other flats this resident also owns/rents.',
    'check_in': 'Check In',
    'check_out': 'Check Out',
    'checked_in': 'Checked In',
    'checked_out': 'Checked Out',
    'cheque': 'Cheque',
    'choose_a_payment_method': 'Choose a payment method',
    'choose_from_gallery': 'Choose from Gallery',
    'close': 'Close',
    'closed': 'Closed',
    'clubhouse': 'Clubhouse',
    'color_palette': 'Color Palette',
    'comment_added': 'Comment added!',
    'comments': 'Comments',
    'community_chat': 'Community Chat',
    'complaint_details': 'Complaint Details',
    'complaint_raised_successfully': 'Complaint raised successfully!',
    'complaints': 'Complaints',
    'complaints_report': 'Complaints Report',
    'confirm': 'Confirm',
    'confirm_password': 'Confirm Password',
    'content': 'Content',
    'create_apply_to_all_flats': 'Create & Apply to All Flats',
    'create_charge': 'Create Charge',
    'currency_code': 'Currency Code',
    'currency_symbol': 'Currency Symbol',
    'current': 'Current',
    'current_fund_balance': 'Current Fund Balance',
    'current_month': 'Current Month',
    'current_password': 'Current Password',
    'dashboard': 'Dashboard',
    'date': 'Date *',
    'delete': 'Delete',
    'delete_apartment': 'Delete apartment',
    'delete_apartment_confirm': 'This will permanently delete this apartment and everything under it (flats, residents, bills, etc). This cannot be undone.',
    'delete_advance_entry_q': 'Delete advance entry?',
    'delete_bill': 'Delete bill',
    'delete_bill_q': 'Delete Bill?',
    'delete_category': 'Delete Category',
    'delete_charge': 'Delete Charge',
    'delete_charge_type': 'Delete Charge Type',
    'delete_expense': 'Delete Expense',
    'delete_facility': 'Delete Facility',
    'delete_flat': 'Delete Flat',
    'delete_floor': 'Delete Floor',
    'delete_notice': 'Delete Notice',
    'delete_slot': 'Delete Slot',
    'delete_tower': 'Delete Tower',
    'delete_vendor': 'Delete Vendor',
    'delivery': 'Delivery',
    'describe_your_issue_or_question_in_detail': 'Describe your issue or question in detail...',
    'description': 'Description',
    'description_2': 'Description *',
    'description_optional': 'Description (optional)',
    'display_label_optional': 'Display Label (optional)',
    'due': 'Due',
    'due_date': 'Due Date',
    'due_date_2': 'Due Date *',
    'e_g_101_a_12': 'e.g. 101, A-12',
    'e_g_1_2_3_or_g_for_ground': 'e.g. 1, 2, 3 or G for Ground',
    'e_g_500': 'e.g. 500',
    'e_g_b1_g': 'e.g. B1, G',
    'e_g_ground_floor_mezzanine': 'e.g. Ground Floor, Mezzanine',
    'e_g_maintenance_water_lift': 'e.g. Maintenance, Water, Lift',
    'e_g_mh_01_ab_1234': 'e.g. MH 01 AB 1234',
    'e_g_p_101': 'e.g. P-101',
    'e_g_tower_a_block_1': 'e.g. Tower A, Block 1',
    'edit': 'Edit',
    'edit_advance_entry': 'Edit Advance Entry',
    'edit_facility': 'Edit Facility',
    'edit_one_time_charge': 'Edit One-Time Charge',
    'email': 'Email',
    'email_address': 'Email Address',
    'emergency': 'Emergency',
    'emergency_numbers': 'SOS Helpline',
    'enter_a_valid_amount': 'Enter a valid amount',
    'enter_a_valid_hex_code_like_1a3c5e': 'Enter a valid hex code like #1A3C5E',
    'enter_email': 'Enter your email address',
    'enter_otp': 'Enter the 6-digit OTP sent to your email',
    'error': 'Error',
    'event': 'Event',
    'event_2': '🎉  Event',
    'expected_arrival': 'Expected Arrival',
    'general_categories': 'General Categories',
    'expense_deleted': 'Expense deleted',
    'expenses': 'Expenses',
    'expenses_by_category': 'Expenses by Category',
    'facilities': 'Facilities',
    'facility': 'Facility',
    'facility_added': 'Facility added!',
    'facility_bookings': 'Facility Bookings',
    'facility_name': 'Facility Name *',
    'facility_name_required': 'Facility name required',
    'filter': 'Filter',
    'financial': 'Financial',
    'financial_report': 'Financial Report',
    'fixed': 'Fixed',
    'flat': 'Flat',
    'flat_deleted': 'Flat deleted',
    'flat_label': 'Flat',
    'flat_number': 'Flat Number',
    'flat_number_2': 'Flat Number *',
    'flat_number_is_required': 'Flat number is required',
    'flat_wise_charge_overrides': 'Flat-wise Charge Overrides',
    'flat_wise_overrides': 'Flat-wise Overrides',
    'flats': 'Flats',
    'floor': 'Floor',
    'floor_2': 'Floor *',
    'floor_deleted': 'Floor deleted',
    'floor_number': 'Floor Number *',
    'floor_number_is_required': 'Floor number is required',
    'floors': 'Floors',
    'forgot_password': 'Forgot Password?',
    'forgot_password_2': 'Forgot Password',
    'elevated_forgot_password_title': 'Super Admin / Company Admin Reset',
    'elevated_forgot_password_link': 'Super Admin / Company Admin? Reset password here',
    'free': 'Free',
    'frequency': 'Frequency',
    'from': 'From',
    'from_month': 'From Month',
    'full_name': 'Full Name',
    'garden': 'Garden',
    'gate_visitor_control': 'Gate & Visitor Control',
    'general': 'General',
    'general_2': '📢  General',
    'generate': 'Generate',
    'generate_bills': 'Generate Bills',
    'generate_bills_this_apartment': 'Generate Bills (this apartment)',
    'generates_one_bill_per_month_for_a_resident_w': 'Generates one bill per month for a resident who missed several months (e.g. hasn\'t paid in 3 months). Can span into the previous year.',
    'go_to_towers': 'Go to Towers',
    'gst_number_optional': 'GST Number (optional)',
    'gym': 'Gym',
    'hall': 'Hall',
    'hello': 'Hello',
    'hex_code': 'Hex code',
    'high': 'High',
    'if_you_re_starting_to_use_this_app_partway_th': 'If you\'re starting to use this app partway through the year, enter the cash/fund balance you already had on hand. It gets added to all collections and expenses to show an accurate running balance.',
    'in_progress': 'In Progress',
    'inactive': 'Inactive',
    'inactive_charges_will_not_appear_in_bill_gene': 'Inactive charges will not appear in bill generation',
    'income_payments_received': 'Income — Payments Received',
    'individual_n_custom_amounts': 'Individual\n(Custom Amounts)',
    'just_now': 'Just now',
    'language_preference': 'Language Preference',
    'leave_blank_to_keep_current_password': 'Leave blank to keep current password',
    'leave_blank_to_use_the_default_amount_for_tha': 'Leave blank to use the default amount for that flat.',
    'let_residents_see_fund_balance_expenses_and_p': 'Let residents see fund balance, expenses, and pending dues.',
    'level': 'Level',
    'level_floor': 'Level / Floor',
    'loading': 'Loading...',
    'logout': 'Logout',
    'low': 'Low',
    'maintenance': 'Maintenance',
    'maintenance_2': '🔧  Maintenance',
    'maintenance_bill': 'Maintenance Bill',
    'maintenance_bills': 'Maintenance Bills',
    'mark_as_apartment_admin': 'Mark as Apartment Admin',
    'link_existing_apartment_admin': 'Link Existing Apartment Admin',
    'none_new_resident': '— None, add a new resident —',
    'linked_admin_keeps_login': 'This Apartment Admin keeps their existing login - only the flat and occupancy details are added.',
    'medium': 'Medium',
    'message': 'Message *',
    'message_2': 'Message',
    'message_the_community': 'Message the community...',
    'month': 'Month',
    'month_maintenance_charge': '/month maintenance charge',
    'monthly_maintenance_charge_optional': 'Monthly Maintenance Charge (optional)',
    'move_in_date': 'Move-In Date',
    'mute_all_notifications': 'Mute All Notifications',
    'my_bookings': 'My Bookings',
    'my_complaints': 'My Complaints',
    'my_parking_slot': 'My Parking Slot',
    'my_pending_bills': 'My Pending Bills',
    'my_subscription': 'My Subscription',
    'name': 'Name',
    'name_required': 'Name required',
    'new_notice': 'New Notice',
    'new_password': 'New Password',
    'new_status': 'New Status',
    'new_support_ticket': 'New Support Ticket',
    'new_ticket': 'New Ticket',
    'no': 'No',
    'no_advance_requests_awaiting_confirmation': 'No advance requests awaiting confirmation',
    'no_advance_transactions_yet': 'No advance transactions yet',
    'no_agreements_added_yet': 'No agreements added yet.',
    'no_bills_found': 'No bills found',
    'no_bookings_found': 'No bookings found',
    'no_bookings_yet': 'No bookings yet',
    'no_categories_yet': 'No categories yet',
    'no_category': '-- No Category --',
    'no_charge_types_yet_ntap_to_add_one': 'No charge types yet.\nTap + to add one.',
    'no_comments_yet': 'No comments yet.',
    'no_complaints_found': 'No complaints found',
    'no_complaints_raised_yet': 'No complaints raised yet',
    'no_data': 'No data found',
    'no_data_2': 'No data',
    'no_emergency_contacts_added_yet': 'No emergency contacts added yet.',
    'no_expenses_found': 'No expenses found',
    'no_expenses_recorded_yet': 'No expenses recorded yet.',
    'no_facilities_available': 'No facilities available',
    'no_facilities_found': 'No facilities found',
    'no_facilities_yet': 'No facilities yet',
    'no_flats_found': 'No flats found',
    'no_flats_match_this_filter': 'No flats match this filter',
    'no_flats_yet_tap_to_add_one': 'No flats yet. Tap + to add one.',
    'no_floors_found': 'No floors found',
    'no_messages_yet_say_hello_to_your_community': 'No messages yet. Say hello to your community!',
    'no_notices_yet': 'No notices yet',
    'no_notifications_yet': 'No notifications yet',
    'no_occupied_flats_found': 'No occupied flats found.',
    'no_occupied_flats_with_a_resident_found': 'No occupied flats with a resident found.',
    'no_one_time_charges_yet': 'No one-time charges yet',
    'no_online_payment_gateway_configured_yet_paid': 'No online payment gateway configured yet. Paid plans require cash payment to the Super Admin, pending approval.',
    'no_other_vacant_flats_available': 'No other vacant flats available',
    'no_parking_slots_found': 'No parking slots found',
    'no_parking_slots_yet': 'No parking slots yet',
    'no_parking_slots_available': 'No parking slots available right now',
    'no_payments_awaiting_confirmation': 'No payments awaiting confirmation',
    'no_pending_dues': 'No pending dues',
    'no_pending_dues_in_the_community_right_now': 'No pending dues in the community right now.',
    'no_push_notification_activities_have_been_ena': 'No push notification activities have been enabled for your apartment yet.',
    'no_residents_found': 'No residents found',
    'search_resident_or_flat': 'Search resident or flat',
    'no_support_tickets_yet': 'No support tickets yet',
    'no_towers_yet_tap_to_add_one': 'No towers yet. Tap + to add one.',
    'no_vehicle_number': 'No vehicle number',
    'no_vendors_found': 'No vendors found',
    'no_visitors': 'No visitors',
    'no_visitors_found': 'No visitors found',
    'no_visitors_yet': 'No visitors yet',
    'normal': 'Normal',
    'not_permanent_can_be_handed_to_someone_else_a': 'Not permanent - can be handed to someone else anytime',
    'notes_optional': 'Notes (optional)',
    'notice_board': 'Notice Board',
    'notice_deleted': 'Notice deleted',
    'notice_published': 'Notice published!',
    'notice_type': 'Notice Type',
    'notices': 'Notices',
    'notification_sent': 'Notification sent!',
    'notification_settings': 'Notification Settings',
    'notification_settings_saved': 'Notification settings saved.',
    'apartment_notification_settings': 'Apartment Notification Settings',
    'apartment_notification_settings_hint': 'Controls which activities send push notifications to your residents, and how often reminders repeat.',
    'pending_payment_reminder_interval': 'Pending Payment Reminder Interval',
    'pending_payment_reminder_interval_hint': 'How often residents with an outstanding bill get a reminder push notification.',
    'agreement_expiry_reminder_interval': 'Agreement Expiry Reminder Interval',
    'agreement_expiry_reminder_interval_hint': 'How often residents get re-notified about an apartment agreement nearing its expiry date.',
    'days_label': 'days',
    'save_apartment_settings': 'Save Apartment Settings',
    'apartment_settings_saved': 'Apartment settings saved.',
    'notifications': 'Notifications',
    'occupancy': 'Occupancy',
    'occupancy_report': 'Occupancy Report',
    'occupancy_type': 'Occupancy Type',
    'occupied': 'Occupied',
    'one_time': 'One-Time',
    'one_time_charge': 'One-Time Charge',
    'one_time_charge_created_and_applied': 'One-time charge created and applied!',
    'one_time_charges': 'One-Time Charges',
    'online': 'Online',
    'open': 'Open',
    'opening_balance': 'Opening Balance',
    'other': 'Other',
    'outstanding': 'Outstanding',
    'overdue': 'Overdue',
    'overview': 'Overview',
    'owner': 'Owner',
    'owners_only': 'Owners Only',
    'paid': 'Paid',
    'paid_amount': 'Paid Amount',
    'parking': 'Parking',
    'parking_slot_requested': 'Parking slot requested!',
    'partial': 'Partial',
    'password': 'Password',
    'password_reset_please_login': 'Password reset! Please login.',
    'pay': 'Pay',
    'pay_directly_by_bank_transfer_upi': 'Pay Directly by Bank Transfer / UPI',
    'bank_details': 'Bank Details',
    'bank_details_updated': 'Bank details updated.',
    'bank_details_shown_to_your_own_apartments': 'These details are shown to Apartment Admins of your own apartments on their "My Subscription" page, as an option alongside cash. All fields are optional.',
    'qr_code_optional': 'QR Code (optional)',
    'bank_account_optional': 'Bank Account (optional)',
    'tap_to_upload': 'Tap to upload',
    'pay_your_platform_subscription': 'Pay Your Platform Subscription',
    'bank_name': 'Bank Name',
    'ifsc_code': 'IFSC Code',
    'account_number': 'Account Number',
    'account_holder_name': 'Account Holder Name',
    'bank_transfer_details_title': 'Transfer To This Account',
    'swift_code': 'SWIFT Code',
    'branch_name': 'Branch Name',
    'pay_now': 'Pay Now',
    'payment_claim_rejected': 'Payment claim rejected',
    'payment_claim_submitted_awaiting_admin_confir': 'Payment claim submitted - awaiting admin confirmation.',
    'payment_claim_withdrawn': 'Payment claim withdrawn.',
    'withdraw_claim': 'Withdraw',
    'withdraw_claim_title': 'Withdraw payment claim?',
    'withdraw_claim_message': 'This will cancel your submitted payment claim so it goes back to unpaid. You can submit it again anytime.',
    'payment_method': 'Payment Method',
    'payment_mode': 'Payment Mode *',
    'payment_recorded': 'Payment recorded!',
    'payment_successful_plan_activated': 'Payment successful. Plan activated!',
    'pending': 'Pending',
    'pending_advance_approvals': 'Pending Advance Approvals',
    'pending_approvals': 'Pending Approvals',
    'pending_dues': 'Pending Dues',
    'pending_dues_by_resident': 'Pending Dues by Resident',
    'pending_one_time_charge_payments': 'Pending One-Time Charge Payments',
    'pending_outstanding': 'Pending / Outstanding',
    'pending_payments': 'Pending Payments',
    'pending_super_admin_approval': 'Pending Super Admin approval',
    'per_sqft': 'Per sqft',
    'period': 'Period',
    'personal': 'Personal',
    'phone': 'Phone',
    'phone_number': 'Phone Number',
    'photo_sharing_isn_t_enabled_for_your_apartmen': 'Photo sharing isn\'t enabled for your apartment yet. Ask your Apartment Admin to check with the Super Admin.',
    'photo_sharing_isn_t_enabled_for_your_apartmen_2': 'Photo sharing isn\'t enabled for your apartment yet — ask your Apartment Admin to check with the Super Admin.',
    'photos': 'Photos',
    'playground': 'Playground',
    'please_fill_in_subject_and_message': 'Please fill in subject and message.',
    'please_select_a_resident': 'Please select a resident',
    'please_select_a_tower': 'Please select a tower',
    'please_select_tower_and_floor': 'Please select tower and floor',
    'pool': 'Pool',
    'post_comment': 'Post Comment',
    'post_notice': 'Post Notice',
    'posted_on': 'Posted On',
    'powered_by': 'Powered by',
    'powered_by_exalted_solution': 'Powered by Exalted Solution',
    'pre_approve': 'Pre-Approve',
    'pre_approve_visitor': 'Pre-Approve Visitor',
    'primary_flat': 'Primary Flat',
    'priority': 'Priority',
    'privacy_policy': 'Privacy Policy',
    'profile': 'Profile',
    'publish_notice': 'Publish Notice',
    'purpose': 'Purpose',
    'purpose_optional': 'Purpose (optional)',
    'quick_actions': 'Quick Actions',
    'raise_complaint': 'Raise Complaint',
    'reason': 'Reason',
    'reason_shown_to_resident': 'Reason (shown to resident)',
    'record': 'Record',
    'record_payment': 'Record Payment',
    'reference_no_optional': 'Reference No. (optional)',
    'reject': 'Reject',
    'reject_advance_claim': 'Reject advance claim?',
    'reject_payment': 'Reject payment?',
    'rejected': 'Rejected',
    'release': 'Release',
    'release_parking_slot': 'Release Parking Slot',
    'release_the_slot_first_before_deleting': 'Release the slot first before deleting',
    'requires_admin_approval': 'Requires admin approval',
    'resend_otp': 'Resend OTP',
    'reserved': 'Reserved',
    'reset_password': 'Reset Password',
    'reset_password_optional': 'Reset Password (optional)',
    'resident': 'Resident',
    'resident_added_successfully': 'Resident added successfully!',
    'resident_directory': 'Resident Directory',
    'resident_financial_visibility': 'Resident Financial Visibility',
    'resident_removed': 'Resident removed.',
    'resident_updated_successfully': 'Resident updated successfully!',
    'resident_view': 'Resident View',
    'remove_resident': 'Remove Resident',
    'confirm_remove_resident': 'Remove',
    'remove_resident_warning': 'This permanently deletes all of their data (bills, payments, wallet, complaints, family members, vehicles, etc.). This cannot be undone.',
    'yes_remove': 'Yes, remove',
    'residents': 'Residents',
    'resolve': 'Resolve',
    'resolved': 'Resolved',
    'retry': 'Retry',
    'rules': 'Rules',
    'save': 'Save',
    'save_changes': 'Save Changes',
    'save_settings': 'Save Settings',
    'search': 'Search',
    'search_by_name_flat_or_phone': 'Search by name, flat or phone...',
    'search_by_name_or_phone': 'Search by name or phone...',
    'search_by_name_phone_or_email': 'Search by name, phone or email...',
    'search_flat_number': 'Search flat number...',
    'search_flat_number_2': 'Search flat number',
    'search_name_or_category': 'Search name or category...',
    'search_vendor_or_category': 'Search vendor or category...',
    'search_vendors': 'Search vendors...',
    'security': 'Security',
    'select_category': 'Select category',
    'select_floor': 'Select floor',
    'select_language': 'Select Language',
    'select_resident': 'Select resident',
    'select_the_same_month_twice_for_a_single_mont': 'Select the same month twice for a single month, or a wider range for several months at once (max 24).',
    'selected_residents': 'Selected Residents',
    'send': 'Send',
    'send_notification_to_residents': 'Send Notification to Residents',
    'send_otp': 'Send OTP',
    'send_push_notification': 'Send push notification',
    'send_to': 'Send To',
    'service': 'Service',
    'set_a_fixed_override_or_a_per_sqft_rate_for_a': 'Set a fixed override or a per-sqft rate for any flat. Leave blank to use the charge type\'s default amount.',
    'set_amount_per_flat': 'Set Amount per Flat',
    'set_opening_balance': 'Set Opening Balance',
    'set_password': 'Set Password',
    'settings': 'Settings',
    'shown_for_community_transparency_only_outstan': 'Shown for community transparency - only outstanding amounts, no payment details.',
    'sign_in': 'Sign In',
    'sign_in_to_continue': 'Sign in to continue',
    'slot': 'Slot',
    'slot_assigned': 'Slot assigned!',
    'slot_deleted': 'Slot deleted',
    'slot_number': 'Slot Number *',
    'slot_number_required': 'Slot number required',
    'slot_released': 'Slot released',
    'slot_type': 'Slot Type',
    'society_finances': 'Society Finances',
    'sound': 'Sound',
    'sound_vibration': 'Sound & Vibration',
    'standard': 'Standard',
    'start': 'Start',
    'status': 'Status',
    'status_updated': 'Status updated!',
    'subject': 'Subject',
    'submit': 'Submit',
    'submit_booking_request': 'Submit Booking Request',
    'submit_complaint': 'Submit Complaint',
    'submit_payment': 'Submit Payment',
    'submitted_for_admin_confirmation_once_approve': 'Submitted for admin confirmation. Once approved, it\'s auto-adjusted against your dues, and any leftover stays as a +ve balance.',
    'success': 'Success',
    'super_admin': 'Super Admin',
    'support_tickets': 'Support Tickets',
    'take_photo': 'Take Photo',
    'tap_a_swatch_to_change_it': 'Tap a swatch to change it',
    'tap_logo_to_change': 'Tap logo to change',
    'tap_the_button_below_to_post_one': 'Tap the button below to post one',
    'tap_to_request': 'Tap to request',
    'tenant': 'Tenant',
    'tenants_only': 'Tenants Only',
    'terms_conditions': 'Terms & Conditions',
    'test_mode': 'Test mode',
    'text': '──────',
    'the_update_file_isn_t_available_right_now_ple': 'The update file isn\'t available right now — please check back shortly.',
    'these_are_applied_once_to_all_occupied_flats': 'These are applied once to all occupied flats',
    'this_resident_has_more_than_one_flat_leave_as': 'This resident has more than one flat. Leave as "All" to catch up every flat, or pick one.',
    'this_ticket_is_closed': 'This ticket is closed.',
    'this_will_be_sent_to_the_admin_for_confirmati': 'This will be sent to the admin for confirmation before it\'s marked paid.',
    'timings': 'Timings',
    'title': 'Title',
    'title_2': 'Title *',
    'title_and_message_required': 'Title and message required',
    'title_and_valid_amount_required': 'Title and valid amount required',
    'to': 'To',
    'to_2': 'to',
    'to_month': 'To Month',
    'today': 'Today',
    'today_s_gate_activity': 'Today\'s Gate Activity',
    'total': 'Total',
    'total_advance_held_all_flats': 'Total Advance Held (All Flats)',
    'total_dues': 'Total Dues',
    'tower': 'Tower',
    'tower_2': 'Tower *',
    'tower_deleted': 'Tower deleted',
    'tower_name': 'Tower Name *',
    'tower_name_is_required': 'Tower name is required',
    'towers': 'Towers',
    'transaction_history': 'Transaction History',
    'transaction_ref_id_optional': 'Transaction / Ref ID (optional)',
    'turns_off_push_notifications_entirely_regardl': 'Turns off push notifications entirely, regardless of settings below',
    'type': 'Type',
    'type_your_reply': 'Type your reply...',
    'unable_to_load_branding': 'Unable to load branding',
    'update_now': 'Update Now',
    'update_required': 'Update Required',
    'update_status': 'Update Status',
    'upi': 'UPI',
    'auto_renew_on': 'Auto-renew on',
    'turn_off': 'Turn off',
    'turn_off_auto_renew_confirm': 'Turn off auto-renew? Your plan stays active until it expires.',
    'auto_renew_turned_off': 'Auto-renew turned off. Your plan stays active until it expires.',
    'enable_auto_renew': 'Enable auto-renew',
    'auto_renew_unavailable_for': 'Auto-renew unavailable for',
    'auto_renew_unsupported_gateway_note': "Auto-renew isn't available yet for plans paid via this gateway - contact Super Admin, or pay each renewal manually.",
    'auto_renew_setup': 'Auto-renew setup',
    'auto_renew_enabled': 'Auto-renew enabled.',
    'could_not_start_auto_renew_setup': 'Could not start auto-renew setup.',
    'could_not_confirm_auto_renew_setup': 'Could not confirm auto-renew setup.',
    'contact_super_admin': 'Contact Super Admin',
    'cancel_subscription': 'Cancel Subscription',
    'cancel_subscription_note': 'This ends your plan and turns off auto-renew. Any refund for unused time is handled separately by the Super Admin.',
    'reason_optional': 'Reason (optional)',
    'confirm_cancellation': 'Confirm Cancellation',
    'subscription_cancelled': 'Subscription cancelled.',
    'pay_via_upi': 'Pay via UPI',
    'pay_online': 'Pay Online (Card / UPI / Netbanking)',
    'pay_online_razorpay': 'Pay Online via Razorpay',
    'online_collection_via_razorpay': 'Online Collection via Razorpay',
    'razorpay_online_collection_hint': "A second online payment option for residents, alongside Cashfree and Bank Transfer. There's nothing to register or verify here — it's set up once by your Super Admin. Money collected via Razorpay is settled to you separately by Super Admin rather than split automatically at payment time.",
    'razorpay_online_active': 'Active — residents can already pay their bills, one-time charges, and wallet deposits online via Razorpay.',
    'razorpay_online_inactive': 'Not available yet — ask your Super Admin to configure Razorpay and switch it on for your apartment.',
    'or_pay_another_way': 'or pay another way',
    'urgent': 'Urgent',
    'urgent_2': '🚨  Urgent',
    'use': 'Use',
    'vehicle_number': 'Vehicle Number',
    'vehicle_number_optional': 'Vehicle Number (optional)',
    'vendor': 'Vendor',
    'vendor_name': 'Vendor Name *',
    'vendor_name_required': 'Vendor name required',
    'vendor_required': 'Vendor required',
    'vendors_payees': 'Vendors / Payees',
    'select_vendor': 'Select vendor',
    'renew_date': 'Renew Date',
    'expire_date': 'Expire Date',
    'dates_required': 'Renew and expire dates are required',
    'expire_date_must_be_after_renew_date': 'Expire date must be after renew date',
    'upload_document_optional': 'Upload Document (optional)',
    'replace_document': 'Replace Document',
    'document_selected': 'Document selected',
    'add_phone_number': 'Add Phone Number',
    'at_least_one_phone_number_required': 'At least one phone number is required',
    'delete_contact': 'Delete Contact',
    'delete_agreement': 'Delete Agreement',
    'edit_contact': 'Edit Contact',
    'edit_agreement': 'Edit Agreement',
    'contact_added': 'Contact added!',
    'contact_updated': 'Contact updated!',
    'contact_deleted': 'Contact deleted!',
    'agreement_added': 'Agreement added!',
    'agreement_updated': 'Agreement updated!',
    'agreement_deleted': 'Agreement deleted!',
    'contact_name': 'Contact Name',
    'verify_otp': 'Verify OTP',
    'vibrate': 'Vibrate',
    'view': 'View',
    'view_all': 'View All',
    'view_document': 'View Document',
    'visiting_which_flat': 'Visiting Which Flat? *',
    'visitor_name': 'Visitor Name',
    'visitor_name_2': 'Visitor Name *',
    'visitor_phone': 'Visitor Phone',
    'visitor_pre_approved': 'Visitor pre-approved!',
    'visitors': 'Visitors',
    'wallet': 'Wallet',
    'welcome': 'Welcome',
    'welcome_back': 'Welcome Back',
    'what_s_new': 'What\'s new',
    'which_flat': 'Which Flat? *',
    'write_a_comment': 'Write a comment...',
    'write_notice_content': 'Write notice content...',
    'year': 'Year',
    'yes': 'Yes',
    'yesterday': 'Yesterday',
    'you_do_not_have_an_assigned_parking_slot_requ': 'You do not have an assigned parking slot. Request one from the list below or contact your apartment admin.',
    'you_have_no_pending_dues': 'You have no pending dues.',
    'your_apartment_admin_controls_which_of_these': 'Your Apartment Admin controls which of these are available. Turn any of these off if you don\'t want to be notified about it.',
    'your_data_is_encrypted_and_never_shared': 'Your data is encrypted and never shared',
    'your_phone_may_show_a_security_warning_during': 'Your phone may show a security warning during installation since this update is delivered ',

    // ── Referral Program ─────────────────────────────────────────────
    'referral': 'Referral',
    'refer_and_earn': 'Refer a society, help them get organized!',
    'refer_a_society': 'Refer a Society',
    'referral_not_setup': 'A referral link hasn\'t been set up for your society yet. Please check back later.',
    'referral_benefit_text': 'Know another society that could use AMS? Share your link below. When they sign up and subscribe to a paid plan, your society gets a discount on its next subscription billing — as a thank you.',
    'referral_link': 'Referral Link',
    'copy': 'Copy',
    'copied': 'Copied!',
    'more': 'More',
    'how_it_works': 'How it works',
    'referral_step_1': 'Share your society\'s referral link with another society.',
    'referral_step_2': 'They fill in a short form; our team verifies and sets them up on AMS.',
    'referral_step_3': 'Once they subscribe to a paid plan, your society earns a discount on its next billing.',
    'referral_credit_info': 'Automatically applied to your next subscription billing.',
    'share_via_whatsapp': 'Share via WhatsApp',
    'share_link': 'Share Link',
    'link_copied_to_clipboard': 'Link copied to clipboard',
    'could_not_open_whatsapp': 'Could not open WhatsApp',

    // ── Menu labels missing from the fallback (needed by VoiceCommandCatalog
    // as well as the on-screen menus - see services/voice_command_catalog.dart) ──
    'chat': 'Chat',
    'bookings': 'Bookings',
    'approvals': 'Approvals',
    'flat_charges': 'Flat Charges',
    'subscription': 'Subscription',
    'community_meeting': 'Meet Live',
    'forum': 'Forum',

    // ── Community Forum (see screens/forum/*.dart) ─────────────────────────
    'community_forum': 'Community Forum',
    'new_discussion': 'New Discussion',
    'start_a_discussion': 'Start a Discussion',
    'no_discussions_yet': 'No discussions yet',
    'discussion_title': 'Discussion Title',
    'discussion_body_hint': 'Share the details of your discussion…',
    'post_discussion': 'Post Discussion',
    'discussion_posted_successfully': 'Your discussion has been posted',
    'reply': 'Reply',
    'replies': 'Replies',
    'no_replies_yet': 'No replies yet',
    'write_a_reply': 'Write a reply…',
    'discussion_closed_to_replies': 'This discussion is closed to new replies',
    'views': 'Views',
    'pinned': 'Pinned',

    // ── Voice Commands ───────────────────────────────────────────────────────
    // Keys here are looked up by services/voice_command_service.dart. When a
    // non-English language is active, the API-fetched translation for each of
    // these keys is what the fuzzy matcher compares the heard speech against -
    // so translating them (same mechanism as every other string in this file)
    // is all that's needed to add voice support in a new language.
    'voice_command': 'Voice Command',
    'voice_tap_mic_to_speak': 'Tap the mic and speak a command',
    'voice_listening': 'Listening…',
    'voice_processing': 'Processing…',
    'voice_heard_prefix': 'Heard: ',
    'voice_not_recognized': "Sorry, I didn't catch a known command. Try again?",
    'voice_or_tap_below': 'Or just tap where you want to go:',
    // One-time onboarding tip shown before a device's very first mic use.
    'voice_onboarding_title': 'Tap the mic, then just say what you want',
    'voice_onboarding_body': "No special phrasing needed - talk like you're asking a person. For example, try saying:",
    'voice_example_open_prefix': 'Open',
    'voice_example_generate_bill': 'Generate bill for Suresh, July',
    'voice_onboarding_ok': 'Got it',
    // On-demand help sheet, opened via the "?" badge on the mic button
    // (separate from the one-time onboarding tip above - this one can be
    // reopened any time).
    'voice_help_title': 'What you can say',
    'voice_help_nav_heading': 'Go anywhere',
    'voice_help_actions_heading': 'Take an action',
    'voice_help_action_generate_bill': 'Generate bill for {name}, {month}',
    'voice_help_action_approve_payment': 'Approve payment for {name}',
    'voice_no_speech': "Didn't hear anything. Try again?",
    'voice_mic_permission_denied': 'Microphone permission is needed for voice commands.',
    'voice_not_available': 'Voice recognition isn\'t available on this device.',
    'voice_try_again': 'Try Again',
    'voice_cancel': 'Cancel',
    'voice_opening': 'Opening',
    'voice_mic_repositioned': 'Mic moved. Long-press it anytime to reset.',
    'voice_mic_reset': 'Mic position reset',
    // Trigger phrases the parser looks for (fuzzy/contains-matched, so close
    // mishearings like "generat a bill" or "genrate bill" still match).
    'voice_trigger_generate_bill': 'generate bill',
    'voice_trigger_approve_payment': 'approve payment',
    'voice_word_for': 'for',
    // Words stripped out of a spoken command before it's fuzzy-matched
    // against a menu label (see VoiceCommandService._stripFillerWords).
    // Comma-separated; longest phrases are matched first.
    'voice_filler_words': 'go to,take me to,navigate to,show me,open,show,goto,launch,view,display,please,can you,could you,i want to,want to,the,page,screen,section',
    // Confirmation screen
    'voice_confirm_action': 'Confirm Voice Command',
    'voice_confirm_generate_bill': 'Generate a catch-up bill for {resident}, {period}?',
    'voice_confirm_approve_payment': 'Approve the pending payment of {amount} for {resident}?',
    'voice_resident_not_found': 'Couldn\'t match "{query}" to a resident. Please pick one:',
    'voice_no_pending_payment': 'No pending payment found for "{query}".',
    'voice_multiple_matches': 'Found more than one close match - please confirm which one:',
    'voice_confirm_and_generate': 'Confirm & Generate',
    'voice_confirm_and_approve': 'Confirm & Approve',
    'voice_resident': 'Resident',
    'voice_period': 'Period',
    'voice_amount': 'Amount',
    'voice_bill_generated': 'Bill generated via voice command',
    'voice_payment_approved': 'Payment approved via voice command',

    // ── New action triggers (resident: raise complaint, add visitor, book
    // facility; admin: reject payment, send notice; security: check
    // in/out; any role: logout) - same fuzzy/contains matching as the
    // triggers above. ─────────────────────────────────────────────────
    'voice_trigger_reject_payment': 'reject payment',
    'voice_trigger_raise_complaint': 'complaint about',
    'voice_trigger_add_visitor': 'add visitor',
    'voice_trigger_book_facility': 'book',
    'voice_trigger_send_notice': 'send notice',
    'voice_trigger_check_in': 'check in',
    'voice_trigger_check_out': 'check out',
    'voice_trigger_logout': 'log out',
    'voice_word_at': 'at',
    'voice_example_raise_complaint': 'Complaint about water leakage',
    'voice_example_add_visitor': 'Add visitor Ramesh, tomorrow 5pm',
    'voice_example_book_facility': 'Book the clubhouse for Saturday',
    'voice_example_check_in': 'Check in Ramesh',
    'voice_help_action_reject_payment': 'Reject payment for {name}',
    'voice_help_action_raise_complaint': 'Complaint about {issue}',
    'voice_help_action_add_visitor': 'Add visitor {name}, {day} {time}',
    'voice_help_action_book_facility': 'Book {facility} for {day}',
    'voice_help_action_send_notice': 'Send notice {message}',
    'voice_help_action_check_in': 'Check in {name}',
    'voice_help_action_check_out': 'Check out {name}',
    'voice_help_action_logout': 'Logout',
    'voice_confirm_reject_payment': 'Reject the pending payment for {resident}?',
    'voice_confirm_raise_complaint': 'Raise this complaint?',
    'voice_confirm_add_visitor': 'Pre-approve this visitor?',
    'voice_confirm_book_facility': 'Submit a booking request for {facility}?',
    'voice_confirm_send_notice': 'Send this notice?',
    'voice_confirm_check_in': 'Check in {visitor}?',
    'voice_confirm_check_out': 'Check out {visitor}?',
    'voice_confirm_logout': 'Are you sure you want to log out?',
    'voice_confirm_and_reject': 'Confirm & Reject',
    'voice_confirm_and_submit': 'Confirm & Submit',
    'voice_confirm_and_send': 'Confirm & Send',
    'voice_confirm_and_check_in': 'Confirm & Check In',
    'voice_confirm_and_check_out': 'Confirm & Check Out',
    'voice_payment_rejected': 'Payment rejected via voice command',
    'voice_notice_sent': 'Notice sent via voice command',
    'voice_visitor_checked_in': 'Visitor checked in via voice command',
    'voice_visitor_checked_out': 'Visitor checked out via voice command',
    'voice_no_matching_visitor': 'Couldn\'t match "{query}" to a visitor.',
    'voice_from': 'From',
    'voice_to': 'To',
    'voice_logout_title': 'Logout',

    // ── Newest action triggers (resident: cancel booking, recharge
    // wallet; admin: resolve complaint; any role: emergency SOS, send
    // chat message) - same fuzzy/contains matching as the triggers above.
    'voice_trigger_cancel_booking': 'cancel booking',
    'voice_trigger_recharge_wallet': 'recharge wallet',
    'voice_trigger_resolve_complaint': 'resolve complaint',
    'voice_trigger_emergency_sos': 'emergency',
    'voice_trigger_send_message': 'send a message',
    'voice_example_cancel_booking': 'Cancel booking for the clubhouse',
    'voice_example_recharge_wallet': 'Recharge wallet 500',
    'voice_example_resolve_complaint': 'Resolve complaint for Priya',
    'voice_example_emergency_sos': 'Emergency',
    'voice_example_send_message': "Send a message, I'm running late",
    'voice_help_action_cancel_booking': 'Cancel booking for {facility}',
    'voice_help_action_recharge_wallet': 'Recharge wallet {amount}',
    'voice_help_action_resolve_complaint': 'Resolve complaint for {name}',
    'voice_help_action_emergency_sos': 'Emergency',
    'voice_help_action_send_message': 'Send a message {text}',
    'voice_confirm_cancel_booking': 'Cancel this booking for {facility}?',
    'voice_confirm_recharge_wallet': 'Submit a wallet top-up of {amount}?',
    'voice_confirm_resolve_complaint': 'Update this complaint\'s status for {resident}?',
    'voice_confirm_send_message': 'Send this message to the community chat?',
    'voice_confirm_and_cancel': 'Confirm & Cancel',
    'voice_confirm_and_call': 'Call Now',
    'voice_booking_cancelled': 'Booking cancelled via voice command',
    'voice_wallet_topup_submitted': 'Wallet top-up submitted via voice command',
    'voice_complaint_status_updated': 'Complaint status updated via voice command',
    'voice_message_sent': 'Message sent via voice command',
    'voice_no_matching_booking': 'Couldn\'t match "{query}" to an active booking.',
    'voice_no_open_complaint': 'No open complaint found for "{query}".',
    'voice_emergency_title': 'Emergency Contacts',
    'voice_emergency_body': 'Tap a contact to call immediately.',
    'voice_no_emergency_contacts': 'No emergency contacts have been set up for this apartment.',

    // ── Latest batch of action triggers (admin: approve/reject booking;
    // resident: pay bill in cash; any role: change language). ───────────
    'voice_trigger_approve_booking': 'approve booking',
    'voice_trigger_reject_booking': 'reject booking',
    'voice_trigger_pay_bill': 'pay bill',
    'voice_trigger_change_language': 'change language',
    'voice_example_approve_booking': 'Approve booking for Priya',
    'voice_example_pay_bill': 'Pay bill in cash',
    'voice_example_change_language': 'Change language to Hindi',
    'voice_help_action_approve_booking': 'Approve booking for {name}',
    'voice_help_action_reject_booking': 'Reject booking for {name}',
    'voice_help_action_pay_bill': 'Pay bill in cash',
    'voice_help_action_change_language': 'Change language to {language}',
    'voice_confirm_approve_booking': 'Approve the pending booking for {resident}?',
    'voice_confirm_reject_booking': 'Reject the pending booking for {resident}?',
    'voice_confirm_pay_bill': 'Submit a cash payment request for {bill}?',
    'voice_confirm_change_language': 'Switch the app language to {language}?',
    'voice_confirm_and_approve_booking': 'Confirm & Approve',
    'voice_confirm_and_reject_booking': 'Confirm & Reject',
    'voice_confirm_and_change': 'Confirm & Change',
    'voice_booking_approved': 'Booking approved via voice command',
    'voice_booking_rejected': 'Booking rejected via voice command',
    'voice_language_changed': 'Language changed via voice command',
    'voice_no_pending_booking': 'No pending booking found for "{query}".',
    'voice_no_outstanding_bill': 'No outstanding bill found for "{query}".',
    'voice_language_not_found': 'Couldn\'t match "{query}" to a supported language.',
    'voice_rejection_reason': 'Reason (optional)',

    // Super Admin & Company Admin screens
    'new_company': 'New Company',
    'company_name': 'Company Name',
    'city_optional': 'City (optional)',
    'first_company_admin_login': 'First Company Admin Login',
    'admin_name': 'Admin Name',
    'admin_email': 'Admin Email',
    'admin_phone': 'Admin Phone',
    'company_name_required': 'Company name is required.',
    'passwords_do_not_match': 'Passwords do not match.',
    'create_company': 'Create Company',
    'companies': 'Companies',
    'no_companies_yet_tap_to_add_one': 'No companies yet. Tap + to add one.',
    'apartments_lc': 'apartments',
    'no_subscription': 'No subscription',
    'edit_apartment': 'Edit Apartment',
    'new_apartment': 'New Apartment',
    'apartment_name': 'Apartment Name',
    'with_towers': 'With Towers',
    'without_towers_direct_flats': 'Without Towers (Direct Flats)',
    'structure': 'Structure',
    'direct_no_company': 'Direct (no Company)',
    'company_optional': 'Company (optional)',
    'address': 'Address',
    'city': 'City',
    'state': 'State',
    'pincode': 'Pincode',
    'please_fill_all_required_fields': 'Please fill all required fields.',
    'create_apartment': 'Create Apartment',
    'apartments': 'Apartments',
    'no_apartments_yet_tap_to_add_one': 'No apartments yet. Tap + to add one.',
    'direct': 'Direct',
    'no_plan': 'No Plan',
    'edit_apartment_admin': 'Edit Apartment Admin',
    'new_apartment_admin': 'New Apartment Admin',
    'email_login': 'Email (login)',
    'new_password_optional': 'New Password (optional)',
    'assign_apartments': 'Assign Apartments',
    'password_is_required': 'Password is required.',
    'select_at_least_one_apartment': 'Select at least one apartment.',
    'create': 'Create',
    'remove_admin': 'Remove Admin',
    'remove': 'Remove',
    'apartment_admins': 'Apartment Admins',
    'no_apartment_admins_yet_tap_to_add_one': 'No Apartment Admins yet. Tap + to add one.',
    'total_flats': 'Total Flats',
    'total_collection_all_time': 'Total Collection',
    'open_complaints_all': 'Open Complaints',
    'recent_apartments': 'Recent Apartments',
    'no_apartments_yet': 'No apartments yet.',
    'no_apartments_found': 'No apartments found',
    'reports': 'Reports',
    'edit_plan': 'Edit Plan',
    'new_company_plan': 'New Company Plan',
    'new_apartment_plan': 'New Apartment Plan',
    'plan_name': 'Plan Name',
    'slug_e_g_yearly_pro': 'Slug (e.g. yearly_pro)',
    'price_currency': 'Price (₹)',
    'duration_days': 'Duration (days)',
    'max_apartments_0_unlimited': 'Max Apartments (0 = unlimited)',
    'max_flats_0_unlimited': 'Max Flats (0 = unlimited)',
    'included_modules': 'Included Modules',
    'create_plan': 'Create Plan',
    'no_apartments': 'No Apartments',
    'no_apartments_to_assign_plan': 'There are no apartments to assign this plan to yet.',
    'amount_received_currency': 'Amount Received (₹)',
    'done': 'Done',
    'plan_assigned': 'Plan assigned.',
    'plans': 'Plans',
    'apartment_plans': 'Apartment Plans',
    'company_plans': 'Company Plans',
    'no_plans_yet_tap_to_create_one': 'No plans yet. Tap + to create one.',
    'days_lc': 'days',
    'max_lc': 'max',
    'flats_lc': 'flats',
    'assign_to_apartment': 'Assign to Apartment',
    'confirm_cash_payment': 'Confirm Cash Payment',
    'subscriptions': 'Subscriptions',
    'no_subscriptions_yet': 'No subscriptions yet.',
    'expires_lc': 'expires',
    'company_dashboard': 'Company Dashboard',
    'my_company': 'My Company',
    'no_active_platform_subscription': 'No active platform subscription. Contact the Super Admin.',
    'subscription_earnings': 'Subscription Earnings',
    'from_your_apartments_plans': "from your apartments' plans",
    'full_report': 'Full Report',
    'your_apartments': 'Your Apartments',
    'total_lc': 'total',
    'my_plans': 'My Plans',
    'no_apartments_to_assign_plan_own': 'You have no apartments to assign this plan to yet.',
    'company_profile': 'Company Profile',
    'saved': 'Saved',
    'company_profile_updated': 'Company profile updated.',
    'contact': 'Contact',
    'contact_phone': 'Contact Phone',
    'contact_email': 'Contact Email',
    'company_report': 'Company Report',
    'your_plans_sold_to_your_apartments': 'Your Plans (sold to your apartments)',
    'no_plans_created_yet': 'No plans created yet.',
    'subscription_history': 'Subscription History',
    'no_history_yet': 'No history yet.',

    // Added: keys that were referenced via t() but had no fallback text,
    // so they were rendering as raw snake_case on screen (parity fix).
    'advance_balance': 'Advance Balance',
    'approve_booking_q': 'Approve this booking?',
    'assign_to_flat': 'Assign to Flat',
    'attendees': 'Attendees',
    'awaiting_confirmation_resolve_first': 'Awaiting confirmation — resolve this first',
    'booking_details': 'Booking Details',
    'fee_payment_status': 'Fee Payment Status',
    'no_bookings_awaiting_approval': 'No bookings awaiting approval',
    'paid_lowered_refunds_raised_tops_up': 'Editing: lower amount = refund, higher = top-up',
    'payment_history': 'Payment History',
    'please_select_a_flat': 'Please select a flat',
    'reject_booking': 'Reject Booking',
    'rejection_reason': 'Rejection Reason',
    'select_flat': 'Select Flat',
    'time': 'Time',
    'view_all_bookings': 'View All Bookings',
  
    // Added: previously-hardcoded UI strings found and routed through
    // the translation system (localization completeness pass).

    'pending_2': 'PENDING',
    'home': 'Home',
    'insights': 'Insights',
    'this_week': 'This Week',
    'compl': 'Compl.',
    'approved_but_fee_not_charged_no_flat_linked': 'Approved but fee not charged - no flat linked',
    'this_facility_already_has_bookings_so_its': 'This facility already has bookings, so its details can\'t be edited or deleted. You can still deactivate it below.',
    'month_2': '/ month',
    'this_apartment_doesnt_use_towers_the_flat_will': 'This apartment doesn\'t use towers — the flat will be added directly.',
    'this_flat_is_already_vacant_no_ownership_change': 'This flat is already vacant — no ownership change flag needed.',
    'vacant': 'Vacant',
    'showing': 'Showing',
    'this_apartment_doesnt_use_towers_the_floor_will': 'This apartment doesn\'t use towers — the floor will be added directly.',
    'all_towers': 'All Towers',
    'payer_name_e_g_tower_company_hall_renter': 'Payer Name (e.g. tower company, hall renter)',
    'delete_income': 'Delete Income',
    'income_deleted': 'Income deleted.',
    'other_income': 'Other Income',
    'add_income': 'Add Income',
    'no_other_income_recorded_yet': 'No other income recorded yet.',
    'reject_request': 'Reject Request',
    'resident_requested_awaiting_your_approval': 'Resident-requested - awaiting your approval',
    'search_by_flat': 'Search by Flat',
    'search_by_resident': 'Search by Resident',
    'clear_filter': 'Clear Filter',
    'select_resident_2': 'Select Resident',
    'this_month': 'This Month',
    'all_time': 'All Time',
    'clear_filter_2': 'Clear filter',
    'filtered': 'Filtered',
    'condensed_all_time_summary_search_a_flat_or': 'Condensed all-time summary. Search a flat or resident above for their full statement.',
    'collection_overview': 'Collection Overview',
    'billed': 'Billed',
    'collected': 'Collected',
    'resolution_rate': 'Resolution Rate',
    'avg_days_to_resolve': 'Avg. Days to Resolve',
    'in_prog': 'In Prog.',
    'rate': 'Rate',
    'rules_updated': 'Rules updated.',
    'text_color': 'Text color',
    'type_a_rule': 'Type a rule…',
    'add_line_below': 'Add line below',
    'delete_line': 'Delete line',
    'speech_recognition_is_not_available_on_this': 'Speech recognition is not available on this device.',
    'couldnt_start_the_microphone_please_try_again': 'Couldn\'t start the microphone. Please try again.',
    'our_team_typically_responds_within_24_hours': 'Our team typically responds within 24 hours',
    'this_apartment_is_set_up_without_towers': 'This apartment is set up without towers.',
    'flats_are_added_directly_under_flats_no_tower': 'Flats are added directly under Flats — no tower/floor needed.',
    'upi_id_and_payee_name_are_required': 'UPI ID and Payee Name are required.',
    'upi_payment_details_updated': 'UPI payment details updated.',
    'upi_payment_settings': 'UPI Payment Settings',
    'upi_id': 'UPI ID *',
    'payee_name': 'Payee Name *',
    'status_active': 'Status: Active',
    'residents_only_see_upi_as_a_payment_option': 'Residents only see UPI as a payment option while this is Active.',
    'vehicle': 'Vehicle',
    'expected': 'Expected',
    'this_cannot_be_undone_blocked_if_already_used': 'This cannot be undone. Blocked if already used against a bill/charge.',
    'choose_an_apartment': 'Choose an Apartment',
    'this_login_is_linked_to_more_than_one_apartment': 'This login is linked to more than one apartment.',
    'welcome_your_14_day_free_trial_has_started': 'Welcome! Your 14-day free trial has started - every feature is unlocked.',
    '14_days_free_all_features_unlocked': '14 DAYS FREE · ALL FEATURES UNLOCKED',
    'register_your_apartment': 'Register Your Apartment',
    'add_your_society_and_create_your_admin_login_in': 'Add your society and create your Admin login in one step.',
    'apartment_details': 'APARTMENT DETAILS',
    'your_admin_login': 'YOUR ADMIN LOGIN',
    'create_apartment_start_free_trial': 'Create Apartment & Start Free Trial',
    'already_registered': 'Already registered?',
    'schedule_meet_live': 'Schedule Meet Live',
    'start_now': 'Start now',
    'schedule': 'Schedule',
    'this_meeting_isnt_ready_to_join_right_now': 'This meeting isn\'t ready to join right now. Please try again shortly.',
    'camera_microphone_needed': 'Camera & Microphone Needed',
    'premium_video_meetings_are_supported_on_the': 'Premium video meetings are supported on the mobile app only.',
    'this_meetings_premium_video_provider_isnt_fully': 'This meeting\'s Premium video provider isn\'t fully configured yet. Contact your Super Admin.',
    'end_meeting': 'End Meeting?',
    'cancel_meeting': 'Cancel Meeting?',
    'live': 'LIVE',
    'end': 'End',
    'leave_meeting': 'Leave Meeting?',
    'leave': 'Leave',
    'your_meeting_opened_in_a_new_browser_tab': 'Your meeting opened in a new browser tab.',
    'if_nothing_opened_your_browser_may_have_blocked': 'If nothing opened, your browser may have blocked the pop-up - tap below to join.',
    'join_meeting': 'Join Meeting',
    'premium_zegocloud_video_meetings_are_supported': 'Premium (ZegoCloud) video meetings are supported on the mobile app only.',
    'complaint': 'Complaint',
    'admin_view': 'Admin View',
    'view_2': 'VIEW',
    'cancel_booking_2': 'Cancel booking?',
    'scheduled_maintenance': 'SCHEDULED MAINTENANCE',
    'well_be_right_back': 'We\'ll be right back',
    'checking_automatically_in_the_background': 'Checking automatically in the background',
    'check_again': 'Check Again',
    'login_as_administrator': 'Login as Administrator',
    'this_login_is_linked_to_more_than_one_apartment_2': 'This login is linked to more than one apartment. Tap one to switch.',
    'current_2': 'current',
    'voice_mic': 'Voice Mic',
    'delete_account': 'Delete Account',
    'continue': 'Continue',
    'confirm_your_password': 'Confirm Your Password',
    'enter_your_password_to_permanently_delete_your': 'Enter your password to permanently delete your account.',
    'your_account_has_been_deleted': 'Your account has been deleted.',
    'use_a_strong_password_with_at_least_8_characters': 'Use a strong password with at least 8 characters.',
    'font_size': 'Font Size',
    'make_text_throughout_the_app_smaller_or_larger': 'Make text throughout the app smaller or larger.',
    'this_is_a_preview_of_the_apps_text_size': 'This is a preview of the app\'s text size.',
    'date_format': 'Date Format',
    'choose_how_dates_are_shown_across_the_app_for': 'Choose how dates are shown across the app for everyone in your apartment.',
    'saving': 'Saving…',
    'community_pending': 'Community Pending',
    'no_rules_published_yet': 'No rules published yet',
    'your_apartment_admin_hasnt_added_any_rules': 'Your apartment admin hasn\'t added any rules.',
    'community_rules_guidelines': 'Community Rules & Guidelines',
    'please_read_through_carefully_these_keep_our': 'Please read through carefully - these keep our community safe and pleasant for everyone.',
    'directory': 'Directory',
    'approval_rate': 'Approval Rate',
    'gate_activity': 'Gate Activity',
    'inside': 'Inside',
    'exited': 'Exited',
    'manage_visitors': 'Manage Visitors',
    'approve_check_in_check_out_visitors': 'Approve, check in & check out visitors',
    'look_up_residents_and_flat_numbers': 'Look up residents and flat numbers',
    'view_slots_assign_release_parking': 'View slots, assign & release parking',
    'view_and_update_complaint_status': 'View and update complaint status',
    'approve_or_reject_booking_requests': 'Approve or reject booking requests',
    'my_profile': 'My Profile',
    'view_and_update_your_profile': 'View and update your profile',
    'visiting': 'Visiting',
    'plan_updated': 'Plan updated.',
    'my_apartments': 'My Apartments',
    'manage_apartments': 'Manage Apartments',
    'switch_apartment': 'Switch Apartment',
    'my_bills': 'My Bills',
    'my_visitors': 'My Visitors',
    'all_my_flats': 'All My Flats',
    'current_language': 'Current Language',
    'step_1_select_country': 'Step 1 — Select Country',
    'choose_your_country': 'Choose your country...',
    'step_2_choose_language': 'Step 2 — Choose Language',
    'select_a_country_first_to_see_available': 'Select a country first to see available languages.',
    'no_languages_found_for_this_country': 'No languages found for this country.',
    'currently_active': 'Currently active',
    'this_sets_your_personal_preference_the': 'This sets your personal preference. The apartment default may differ.',
    'you_are_not_now_apartment_admin_if_you_submit': 'You are not now apartment admin, if you submit then you will be logged out.',
    'set_your_apartments_upi_id_and_payee_name_then': 'Set your apartment\'s UPI ID and payee name, then switch Status to Active to let residents pay pending maintenance bills, one-time charges, and wallet deposits by UPI.',
    'deleting_your_account_will_permanently_remove': 'Deleting your account will permanently remove your account and associated personal data. This action cannot be undone.\n\nSome information may be retained where required for legal, security, financial, or regulatory purposes.\n\nAre you sure you want to continue?',
  };
}
